# -*- coding: utf-8 -*-
"""mainTest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gPjBdk6PhVxzLH9pN9Ldx_U5BpCmAgk-
"""

import cv2
from keras.models import load_model
from PIL import Image
import numpy as np

model = load_model('BrainTumorModel.h5')
image = cv2.imread('/content/pred/pred35.jpg')

img = Image.fromarray(image)
img = img.resize((64, 64))
img = np.array(img)

input_img = np.expand_dims(img, axis=0)
prediction = model.predict(input_img)
results = np.argmax(prediction, axis=1)

print(results)