# -*- coding: utf-8 -*-
"""modelConverter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vBuq2i8RhuK8dtluXO4IXt7-fIeDpw4k
"""

from keras.models import load_model
import tensorflow as tf

model = load_model('BrainTumorModel.h5')

converter = tf.lite.TFLiteConverter.from_keras_model(model)
tf_lite_model = converter.convert()

with open('model.tflite', 'wb') as f:
  f.write(tf_lite_model)